apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: internal
      port: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0-external
spec:
  type: NodePort
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
    - name: external
      port: 9092
      targetPort: 9092
      nodePort: 30092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-external
spec:
  type: NodePort
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
    - name: external
      port: 9093
      targetPort: 9093
      nodePort: 30093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-external
spec:
  type: NodePort
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 30094
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka-headless"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.1
          ports:
            - containerPort: 9092
              name: external-0
            - containerPort: 9093
              name: external-1
            - containerPort: 9094
              name: external-2
            - containerPort: 29092
              name: internal
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper-headless:2181,zookeeper-1.zookeeper-headless:2181,zookeeper-2.zookeeper-headless:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_SNAPSHOT_TRUST_EMPTY
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -e
              ORDINAL=$(echo ${POD_NAME} | awk -F- '{print $NF}')
              
              # Broker ID must be an integer
              export KAFKA_BROKER_ID=$((ORDINAL + 1))
              
              # Listeners for internal and external traffic
              EXTERNAL_PORT=$((9092 + ORDINAL))
              export KAFKA_LISTENERS="INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:${EXTERNAL_PORT}"
              
              # Advertised listeners for clients to connect
              NODE_PORT=$((30092 + ORDINAL))
              # Assuming localhost for local development (e.g., minikube). 
              # Replace with your node's actual external IP in a production environment.
              EXTERNAL_HOST="localhost"
              export KAFKA_ADVERTISED_LISTENERS="INTERNAL://${POD_NAME}.kafka-headless:29092,EXTERNAL://${EXTERNAL_HOST}:${NODE_PORT}"
              
              # Execute the original Confluent entrypoint
              /etc/confluent/docker/run
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
