apiVersion: v1
kind: Service
metadata:
  name: rest-proxy
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: rest-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-proxy
  template:
    metadata:
      labels:
        app: rest-proxy
    spec:
      containers:
        - name: rest-proxy
          image: confluentinc/cp-kafka-rest:7.4.1
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_REST_HOST_NAME
              value: "rest-proxy"
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: "kafka-0.kafka-headless:29092,kafka-1.kafka-headless:29092,kafka-2.kafka-headless:29092"
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8082"