apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  #clusterIP: None
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: server
      port: 2888
      protocol: TCP
    - name: leader-election
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper-headless"
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      volumes:
        - name: zookeeper-jaas-config
          secret:
            secretName: zookeeper-jaas-config
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.1
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZOOKEEPER_SASL_ENABLED
              value: "true"
            - name: ZOOKEEPER_AUTH_PROVIDER_1
              value: "org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
            - name: ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME
              value: "sasl"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: KAFKA_OPTS
              value: "-Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper_jaas.conf"
            - name: ZOO_MY_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-0.zookeeper-headless:2888:3888;2181 server.2=zookeeper-1.zookeeper-headless:2888:3888;2181 server.3=zookeeper-2.zookeeper-headless:2888:3888;2181"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
            - name: zookeeper-log
              mountPath: /var/lib/zookeeper/log
            - name: zookeeper-jaas-config
              mountPath: /etc/zookeeper/secrets
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    set -e
                    # Extract the ordinal from the hostname (e.g., zookeeper-0 -> 0)
                    ORDINAL=$(echo ${ZOO_MY_ID} | awk -F- '{print $NF}')
                    # ZOO_MY_ID should be 1-based
                    MY_ID=$((ORDINAL + 1))
                    echo $MY_ID > /var/lib/zookeeper/data/myid
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: zookeeper-log
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
